export const ApiPaths = {
  BRANDS: "/brands",
  SEARCH: "/search",
  BANNERS: "/banners",
  CATEGORIES: "/categories",
  CATEGORY_HIERARCHY: "/categories/hierarchy",
  CATEGORY: "/category",
  SUBCATEGORY: "/subcategory",
  SUBCATEGORY2: "/subcategory2",
  SUBCATEGORIES: "/subcategories",
  SUBCATEGORIES2: "/subcategories2",
  FAQS: "/faqs",
  BLOGS: "/blogs",
  USERS: "/users",
  USER: "/user", // Add this line
  HOME: "/home/products",
  ALL_PRODUCTS: "/all/products",
  WISHLIST: "/favorites/user",
  FAVORITES: "/favorites",
  CART: "/cart",
  CART_USER: "/cart/user",
  PRODUCTS: "/products",
  ADDRESSES: "/addresses",
  ADDRESSES_USER: "/addresses/user",
  ORDER_USER: "/order/user",
  CANCEL_ORDER: "/order/cancel",
  PLACE_ORDER: "/placeOrder",
  RATING: "/ratings",
  UPLOAD: "/upload",
  BEST_SELLERS: "/admin/bestSellers",
  RECENT_VIEWS: "/recentViews",
  COMBO_CATEGORIES: "/admin/combo-categories-with-products",
  COMBO_PRODUCT: "/admin/combo-product",
  PRODUCTS_BY_CATEGORY: "/products-by-category",

  // Shipping endpoints
  SHIPPING_TRACK: "/shipping/track",
  SHIPPING_SERVICEABILITY: "/shipping/serviceability",
};
// ABOUTFITNESS : "/aboutfitness",
